[build]
builder = "NIXPACKS"
buildCommand = "npx nx build website"
watchPatterns = ["/frontend"]

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npx nx run website:build:development"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
