[build]
builder = "NIXPACKS"
buildCommand = "npx nx build frontend"


[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npx nx run frontend:serve:production"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
